name: CI/CD Pipeline for React App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: ./build  # Change this to your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the successful completion of the 'build' job

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-app-build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          stale-process-killing: true
          branch: gh-pages  # Change this to the branch you use for deployments (e.g., main)
          publish-dir: ./build  # Change this to your build output directory
